# Generated by Django 2.2.4 on 2022-08-10 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0006_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('type', models.CharField(choices=[('START', 'START'), ('STOP', 'STOP')], max_length=8, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='dropship.Project')),
            ],
        ),
    ]
