# Generated by Django 2.2.4 on 2022-08-10 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0014_auto_20220810_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='watchers',
            field=models.ManyToManyField(null=True, related_name='issuedWatched', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(null=True, related_name='issues', to='dropship.Label'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='dropship.Sprint'),
        ),
        migrations.DeleteModel(
            name='watcher',
        ),
    ]
